
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\x08u]\xcc"kT\xee\xcc\xd2\x85o:\xee\xf5\xfd'
    
_lr_action_items = {'id':([0,3,5,7,9,10,11,12,13,14,15,16,17,19,20,22,23,24,25,26,27,28,],[1,1,-6,-1,-1,-1,-1,-9,-10,-16,-5,1,-8,-14,-7,-1,-1,-1,-15,-12,-11,-13,]),'num':([7,18,],[10,22,]),'$end':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17,19,20,22,23,24,25,26,27,28,],[-1,-2,-1,0,-6,-4,-1,-3,-1,-1,-1,-9,-10,-16,-5,-8,-14,-7,-1,-1,-1,-15,-12,-11,-13,]),'RBRACE':([3,5,6,7,8,9,10,11,12,13,14,15,16,17,19,20,21,22,23,24,25,26,27,28,],[-1,-6,-4,-1,-3,-1,-1,-1,-9,-10,-16,-5,-1,-8,-14,-7,25,-1,-1,-1,-15,-12,-11,-13,]),'LBRACE':([7,9,10,11,12,13,17,19,20,22,23,24,26,27,28,],[-1,16,-1,-1,-9,-10,-8,-14,-7,-1,-1,-1,-12,-11,-13,]),'COLON':([1,],[7,]),'COMMA':([10,11,22,23,24,],[18,18,18,18,18,]),'string':([7,18,],[11,23,]),'specialkeyword':([7,18,],[12,24,]),'BIGLIST':([0,3,5,7,9,10,11,12,13,14,15,16,17,19,20,22,23,24,25,26,27,28,],[5,5,-6,-1,-1,-1,-1,-9,-10,-16,-5,5,-8,-14,-7,-1,-1,-1,-15,-12,-11,-13,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'OptionalThings2':([10,11,22,23,24,],[17,20,26,27,28,]),'OptionalBraceBlock':([9,],[15,]),'OptionalThings':([7,],[9,]),'DefList':([0,3,16,],[2,8,21,]),'Definition':([0,3,16,],[3,3,3,]),'S':([0,],[4,]),'epsilon':([0,3,7,9,10,11,16,22,23,24,],[6,6,13,14,19,19,6,19,19,19,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('epsilon -> <empty>','epsilon',0,'p_epsilon','/home/jhudson/shawnee/14/etgg2801/progs/fbx/parsefbx.py',75),
  ('S -> DefList','S',1,'p_S','/home/jhudson/shawnee/14/etgg2801/progs/fbx/parsefbx.py',84),
  ('DefList -> Definition DefList','DefList',2,'p_DefList','/home/jhudson/shawnee/14/etgg2801/progs/fbx/parsefbx.py',88),
  ('DefList -> epsilon','DefList',1,'p_DefList','/home/jhudson/shawnee/14/etgg2801/progs/fbx/parsefbx.py',89),
  ('Definition -> id COLON OptionalThings OptionalBraceBlock','Definition',4,'p_Definition','/home/jhudson/shawnee/14/etgg2801/progs/fbx/parsefbx.py',102),
  ('Definition -> BIGLIST','Definition',1,'p_Definition2','/home/jhudson/shawnee/14/etgg2801/progs/fbx/parsefbx.py',112),
  ('OptionalThings -> string OptionalThings2','OptionalThings',2,'p_OptionalThings','/home/jhudson/shawnee/14/etgg2801/progs/fbx/parsefbx.py',122),
  ('OptionalThings -> num OptionalThings2','OptionalThings',2,'p_OptionalThings','/home/jhudson/shawnee/14/etgg2801/progs/fbx/parsefbx.py',123),
  ('OptionalThings -> specialkeyword','OptionalThings',1,'p_OptionalThings','/home/jhudson/shawnee/14/etgg2801/progs/fbx/parsefbx.py',124),
  ('OptionalThings -> epsilon','OptionalThings',1,'p_OptionalThings','/home/jhudson/shawnee/14/etgg2801/progs/fbx/parsefbx.py',125),
  ('OptionalThings2 -> COMMA string OptionalThings2','OptionalThings2',3,'p_OptionalThings2','/home/jhudson/shawnee/14/etgg2801/progs/fbx/parsefbx.py',134),
  ('OptionalThings2 -> COMMA num OptionalThings2','OptionalThings2',3,'p_OptionalThings2','/home/jhudson/shawnee/14/etgg2801/progs/fbx/parsefbx.py',135),
  ('OptionalThings2 -> COMMA specialkeyword OptionalThings2','OptionalThings2',3,'p_OptionalThings2','/home/jhudson/shawnee/14/etgg2801/progs/fbx/parsefbx.py',136),
  ('OptionalThings2 -> epsilon','OptionalThings2',1,'p_OptionalThings2','/home/jhudson/shawnee/14/etgg2801/progs/fbx/parsefbx.py',137),
  ('OptionalBraceBlock -> LBRACE DefList RBRACE','OptionalBraceBlock',3,'p_OptionalBraceBlock','/home/jhudson/shawnee/14/etgg2801/progs/fbx/parsefbx.py',146),
  ('OptionalBraceBlock -> epsilon','OptionalBraceBlock',1,'p_OptionalBraceBlock','/home/jhudson/shawnee/14/etgg2801/progs/fbx/parsefbx.py',147),
]
